[package]
name = "blink1_stm32"
version = "0.1.2"
edition = "2021"
authors = ["JR.Kim <jrkim@naver.com>"]

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
panic-halt = "0.2"

[dependencies.stm32f1xx-hal]
version = "0.10.0"
features = ["rt", "stm32f103", "medium"]
